site_title="example.site"
site_copyright="© 2025 Max Mustermann"
theme="default"
text_toggle=false
social_button=false
download_button=false
extract_colors=false
download_readme="All rights reserved Max Mustermann"
backgroundcolor="#000000"
